# Extracting dependency graph from sbt with: https://github.com/marketplace/actions/sbt-dependency-submission
name: Update Dependency Graph
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  dependency-graph:
    timeout-minutes: 15
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: scalacenter/sbt-dependency-submission@v2.2.0
